steps:
# 1. Build the Docker image using the Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  args: 
    [
      'build', 
      '-t', 
      'us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA', 
      '.'
    ]

# 2. Push the built Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA']

# 3. Deploy the new image to the existing Cloud Run service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'my-api-service' # This is the name of your Cloud Run service
    - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'

# This tells Cloud Build where to store the final image
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA'

# --- ADD THIS NEW SECTION AT THE END ---
# This option tells Cloud Build to send logs directly to Cloud Logging,
# which is required by your organization's security policy.
options:
  logging: CLOUD_LOGGING_ONLY