steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA', '.']
  id: 'Build Image'

# Step 2: Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA']
  waitFor: ['Build Image']
  id: 'Push Image'

# --- NEW STEP 3: Restore the EF Core Tool ---
# This step reads the .config/dotnet-tools.json file and installs the 'dotnet-ef' tool.
- name: 'mcr.microsoft.com/dotnet/sdk:8.0'
  entrypoint: 'dotnet'
  args: ['tool', 'restore']
  waitFor: ['Push Image']
  id: 'Restore EF Tool'

# Step 4: Run Database Migrations
# This step can now find and use the 'dotnet ef' command.
- name: 'gcr.io/google-appengine/exec-wrapper'
  args:
    - '-i'
    - 'mcr.microsoft.com/dotnet/sdk:8.0'
    - '-s'
    - 'winged-polygon-485011-t1:us-central1:my-dotnet-db-mysql'
    - '--'
    - 'dotnet'
    - 'ef'
    - 'database'
    - 'update'
    - '--project'
    - 'GCP_Pratice.csproj'
  waitFor: ['Restore EF Tool'] # This now waits for the tool to be restored.
  id: 'Run Migrations'

# Step 5: Deploy the image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'my-api-service'
    - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances=winged-polygon-485011-t1:us-central1:my-dotnet-db-mysql'
    - '--set-env-vars=ConnectionStrings__DefaultConnection=Server=/cloudsql/winged-polygon-485011-t1:us-central1:my-dotnet-db-mysql;Database=mydotnetapp_db;Uid=api_user;Pwd=8688050907@Vasu'
  waitFor: ['Run Migrations']
    
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY