steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA', '.']
  id: 'Build Image'

# Step 2: Push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA']
  waitFor: ['Build Image']
  id: 'Push Image'

# Step 3: Clean, Restore Tools, and Run Migrations
- name: 'mcr.microsoft.com/dotnet/sdk:8.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
      echo "Cleaning and Restoring project..."
      dotnet clean GCP_Pratice.csproj
      dotnet restore GCP_Pratice.csproj
      
      echo "Downloading and starting Cloud SQL Proxy..."
      curl -o /usr/local/bin/cloud_sql_proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.0/cloud-sql-proxy.linux.amd64
      chmod +x /usr/local/bin/cloud_sql_proxy
      
      # Start proxy in the background
      /usr/local/bin/cloud_sql_proxy winged-polygon-485011-t1:us-central1:my-dotnet-db-mysql > proxy.log 2>&1 &
      
      # --- THE CORRECTED WAIT LOOP ---
      echo "Waiting for the Cloud SQL socket to be available..."
      for i in {1..20}; do
        # The -S flag checks for a SOCKET file, which is correct. -d was wrong.
        if [ -S "/cloudsql/winged-polygon-485011-t1:us-central1:my-dotnet-db-mysql" ]; then
          echo "Cloud SQL socket is ready!"
          break
        fi
        echo "Waiting... (attempt $i)"
        sleep 1
      done
      
      # Final check after the loop
      if [ ! -S "/cloudsql/winged-polygon-485011-t1:us-central1:my-dotnet-db-mysql" ]; then
        echo "Error: Cloud SQL socket did not appear after 20 seconds."
        echo "--- Proxy Logs ---"
        cat proxy.log
        exit 1
      fi
      
      echo "Restoring dotnet-ef tool..."
      dotnet tool restore
      
      echo "Running database migrations..."
      dotnet ef database update --project GCP_Pratice.csproj
  id: 'Run Migrations'
  waitFor: ['Push Image']

# Step 4: Deploy the image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'my-api-service'
    - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--add-cloudsql-instances=winged-polygon-485011-t1:us-central1:my-dotnet-db-mysql'
    - '--set-env-vars=ConnectionStrings__DefaultConnection=Server=/cloudsql/winged-polygon-485011-t1:us-central1:my-dotnet-db-mysql;Database=mydotnetapp_db;Uid=api_user;Pwd=8688050907@Vasu'
  waitFor: ['Run Migrations']
    
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/dotnet-apps/my-web-api:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY